/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package autorefresh;

import java.awt.Color;
import java.awt.Frame;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JTabbedPane;

/**
 *
 * @author Angular
 */
public class mainframe extends javax.swing.JFrame implements Runnable{
    private FileWriter output;
    private BufferedWriter boutput;
    private int xMouse;
    private int yMouse;
    private Thread t;
    public mainframe() {
        initComponents();
        setIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgpanel = new javax.swing.JPanel();
        headerpanel = new javax.swing.JPanel();
        EXITbtn = new javax.swing.JButton();
        MINbtn = new javax.swing.JButton();
        Iconlab = new javax.swing.JLabel();
        title = new javax.swing.JLabel();
        bannerPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        bottompanel = new javax.swing.JPanel();
        buttonPanel = new javax.swing.JPanel();
        Stoplab = new javax.swing.JLabel();
        Stoppanel = new javax.swing.JPanel();
        Stopbtn = new javax.swing.JButton();
        Startpanel = new javax.swing.JPanel();
        Startbtn = new javax.swing.JButton();
        Startlab = new javax.swing.JLabel();
        bannerlab = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        bgpanel.setBackground(new java.awt.Color(255, 255, 255));
        bgpanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 255, 255)));

        headerpanel.setBackground(new java.awt.Color(255, 255, 255));
        headerpanel.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        headerpanel.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                headerpanelMouseDragged(evt);
            }
        });
        headerpanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                headerpanelMousePressed(evt);
            }
        });

        EXITbtn.setBackground(new java.awt.Color(255, 255, 255));
        EXITbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/Exit.png"))); // NOI18N
        EXITbtn.setContentAreaFilled(false);
        EXITbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        EXITbtn.setOpaque(true);
        EXITbtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/Exit (2).png"))); // NOI18N
        EXITbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EXITbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EXITbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EXITbtnMouseExited(evt);
            }
        });

        MINbtn.setBackground(new java.awt.Color(255, 255, 255));
        MINbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/Minimize.png"))); // NOI18N
        MINbtn.setContentAreaFilled(false);
        MINbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        MINbtn.setOpaque(true);
        MINbtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/Minimize (2).png"))); // NOI18N
        MINbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MINbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MINbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MINbtnMouseExited(evt);
            }
        });

        Iconlab.setBackground(new java.awt.Color(245, 245, 245));
        Iconlab.setFont(new java.awt.Font("Britannic Bold", 1, 14)); // NOI18N
        Iconlab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Iconlab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/icons8_Refresh_20px_3.png"))); // NOI18N
        Iconlab.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Iconlab.setOpaque(true);
        Iconlab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IconlabMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IconlabMouseExited(evt);
            }
        });

        title.setBackground(new java.awt.Color(255, 255, 255));
        title.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(52, 168, 228));
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("AutoRefresh");
        title.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        title.setOpaque(true);

        javax.swing.GroupLayout headerpanelLayout = new javax.swing.GroupLayout(headerpanel);
        headerpanel.setLayout(headerpanelLayout);
        headerpanelLayout.setHorizontalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerpanelLayout.createSequentialGroup()
                .addComponent(Iconlab, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(MINbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(EXITbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        headerpanelLayout.setVerticalGroup(
            headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Iconlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(headerpanelLayout.createSequentialGroup()
                .addGroup(headerpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(EXITbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MINbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(title, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        bannerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/auto-refresh-single-page-wordpress-plugin.jpg"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5), javax.swing.BorderFactory.createTitledBorder("")));
        jLabel1.setOpaque(true);

        javax.swing.GroupLayout bannerPanelLayout = new javax.swing.GroupLayout(bannerPanel);
        bannerPanel.setLayout(bannerPanelLayout);
        bannerPanelLayout.setHorizontalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 364, Short.MAX_VALUE)
        );
        bannerPanelLayout.setVerticalGroup(
            bannerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.setBackground(new java.awt.Color(51, 204, 255));
        jTabbedPane1.setForeground(new java.awt.Color(51, 153, 255));
        jTabbedPane1.setOpaque(true);

        bottompanel.setBackground(new java.awt.Color(255, 255, 255));

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        Stoplab.setBackground(new java.awt.Color(255, 177, 18));
        Stoplab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Stoplab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Stoplab.setText("Stop");
        Stoplab.setOpaque(true);

        Stoppanel.setBackground(new java.awt.Color(255, 255, 255));

        Stopbtn.setBackground(new java.awt.Color(255, 255, 255));
        Stopbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/icons8_Stop_Sign_100px_4.png"))); // NOI18N
        Stopbtn.setContentAreaFilled(false);
        Stopbtn.setOpaque(true);
        Stopbtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/icons8_Stop_Sign_104px.png"))); // NOI18N
        Stopbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StopbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout StoppanelLayout = new javax.swing.GroupLayout(Stoppanel);
        Stoppanel.setLayout(StoppanelLayout);
        StoppanelLayout.setHorizontalGroup(
            StoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stopbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StoppanelLayout.setVerticalGroup(
            StoppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Stopbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        Startpanel.setBackground(new java.awt.Color(255, 255, 255));

        Startbtn.setBackground(new java.awt.Color(255, 255, 255));
        Startbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/icons8_Rocket_100px_1.png"))); // NOI18N
        Startbtn.setContentAreaFilled(false);
        Startbtn.setOpaque(true);
        Startbtn.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/icons8_Rocket_104px.png"))); // NOI18N
        Startbtn.setVerifyInputWhenFocusTarget(false);
        Startbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                StartbtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout StartpanelLayout = new javax.swing.GroupLayout(Startpanel);
        Startpanel.setLayout(StartpanelLayout);
        StartpanelLayout.setHorizontalGroup(
            StartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Startbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        StartpanelLayout.setVerticalGroup(
            StartpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Startbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
        );

        Startlab.setBackground(new java.awt.Color(112, 98, 228));
        Startlab.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Startlab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Startlab.setText("Start");
        Startlab.setOpaque(true);

        bannerlab.setBackground(new java.awt.Color(255, 255, 255));
        bannerlab.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bannerlab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/autorefresh/images.png"))); // NOI18N
        bannerlab.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), javax.swing.BorderFactory.createTitledBorder("")));
        bannerlab.setOpaque(true);

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Startpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Startlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Stoppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Stoplab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bannerlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(20, 20, 20))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Stoplab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Startlab, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, 0)
                .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Startpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Stoppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(36, 36, 36)
                .addComponent(bannerlab, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout bottompanelLayout = new javax.swing.GroupLayout(bottompanel);
        bottompanel.setLayout(bottompanelLayout);
        bottompanelLayout.setHorizontalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
            .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bottompanelLayout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        bottompanelLayout.setVerticalGroup(
            bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 536, Short.MAX_VALUE)
            .addGroup(bottompanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bottompanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("tab1", bottompanel);

        javax.swing.GroupLayout bgpanelLayout = new javax.swing.GroupLayout(bgpanel);
        bgpanel.setLayout(bgpanelLayout);
        bgpanelLayout.setHorizontalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerpanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bannerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        bgpanelLayout.setVerticalGroup(
            bgpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgpanelLayout.createSequentialGroup()
                .addComponent(headerpanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bannerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bgpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EXITbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITbtnMouseExited
        EXITbtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_EXITbtnMouseExited

    private void EXITbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITbtnMouseEntered
        EXITbtn.setBackground(new Color(251, 14, 38));
    }//GEN-LAST:event_EXITbtnMouseEntered

    private void EXITbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EXITbtnMouseClicked
        File f=new File(System.getProperty("user.dir")+"/"+"Stop.ps1");
        try{
        if(!f.exists()){
                String command="$terminator=Get-Process -Name powershell\n" +"Stop-Process $terminator";
                output=new FileWriter(f);
                boutput=new BufferedWriter(output);
                boutput.write(command);
                boutput.close();
                output.close();
                       
        }
        String command1="powershell -executionPolicy bypass -file "+f.getPath();
           Process powershell;
           powershell = Runtime.getRuntime().exec(command1);
           powershell.waitFor();
            } catch (IOException | InterruptedException ex) {
                Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
            }
        System.exit(0);
    }//GEN-LAST:event_EXITbtnMouseClicked

    private void MINbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINbtnMouseExited
        MINbtn.setBackground(new Color(255, 255, 255));
    }//GEN-LAST:event_MINbtnMouseExited

    private void MINbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINbtnMouseEntered
        MINbtn.setBackground(new Color(229, 229, 229));
    }//GEN-LAST:event_MINbtnMouseEntered

    private void MINbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MINbtnMouseClicked
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_MINbtnMouseClicked

    private void IconlabMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconlabMouseEntered
       Iconlab.setBackground(new Color(235, 235, 235));
    }//GEN-LAST:event_IconlabMouseEntered

    private void IconlabMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IconlabMouseExited
        Iconlab.setBackground(new Color(245, 245, 245));
    }//GEN-LAST:event_IconlabMouseExited

    private void headerpanelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerpanelMousePressed
          xMouse=evt.getX();
          yMouse=evt.getY();
    }//GEN-LAST:event_headerpanelMousePressed

    private void headerpanelMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_headerpanelMouseDragged
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_headerpanelMouseDragged

    private void StartbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StartbtnMouseClicked
        Startbtn.setEnabled(false);
        t=new Thread(this);
        t.start();
    }//GEN-LAST:event_StartbtnMouseClicked

    private void StopbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StopbtnMouseClicked
        File f=new File(System.getProperty("user.dir")+"/"+"Stop.ps1");
        try{
            if(!f.exists()){
                String command="$terminator=Get-Process -Name powershell\n" +"Stop-Process $terminator";
                output=new FileWriter(f);
                boutput=new BufferedWriter(output);
                boutput.write(command);
                boutput.close();
                output.close();

            }
            String command1="powershell -executionPolicy bypass -file "+f.getPath();
            Process powershell;
            powershell = Runtime.getRuntime().exec(command1);
            powershell.waitFor();
        } catch (IOException | InterruptedException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_StopbtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
                new mainframe().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXITbtn;
    private javax.swing.JLabel Iconlab;
    private javax.swing.JButton MINbtn;
    private javax.swing.JButton Startbtn;
    private javax.swing.JLabel Startlab;
    private javax.swing.JPanel Startpanel;
    private javax.swing.JButton Stopbtn;
    private javax.swing.JLabel Stoplab;
    private javax.swing.JPanel Stoppanel;
    private javax.swing.JPanel bannerPanel;
    private javax.swing.JLabel bannerlab;
    private javax.swing.JPanel bgpanel;
    private javax.swing.JPanel bottompanel;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JPanel headerpanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables

   
    public void run() {
        try {
           File f=new File(System.getProperty("user.dir")+"/"+"refresh.ps1");
           if(!f.exists()){
    String command;
               command = "$date =get-date"+System.getProperty("line.separator")+"    $deadline=$date.AddMinutes(30)"+System.getProperty("line.separator")+"    while(1) { # Loop forever"+System.getProperty("line.separator")+"    sleep -Seconds 5 # Wait 5 seconds\n    if($date -gt $deadline)\n    {  break; }\n    $wshell = New-Object -ComObject wscript.shell\n    if($wshell.AppActivate('Chrome')) { # Switch to Chrome\n    Sleep 1 # Wait for Chrome to activate\n     $wshell.SendKeys('{F5}')  # Send F5 (Refresh)\n }"
                       +"else { break; } # Chrome not open, exit the loop\n" +
                       "    $date=get-date\n" +
                       "    \n" +    
                       "}";
           output=new FileWriter(f);
           boutput=new BufferedWriter(output);
           boutput.write(command);
           boutput.flush();
           boutput.close();
           output.close();
           }
           String command1="powershell -executionPolicy bypass -file "+f.getPath();
           Process powershell;
           powershell = Runtime.getRuntime().exec(command1);
           powershell.waitFor();
           Startbtn.setEnabled(true);
  }     catch (IOException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(mainframe.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   private void setIcon(){
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icons8_Refresh_20px_3.png")));
   }
}
